services:
  Mongo.Config.StartWars:
    factory:
      class: ../../../context/shared/infrastructure/persistance/mongo/MongoConfigFactory
      method: 'createConfig'
    arguments: ['typesctipt-backend-starwars']
  
  Mongo.Connection.Manager.StartWars:
    factory:
      class: '../../../context/shared/infrastructure/persistance/mongo/MongoClientFactory'
      method: 'createClient'
    arguments: ['typesctipt-backend-starwars', '@Mongo.Config.StartWars']
